# Generated by Django 4.0.3 on 2022-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
